### ISSUE TITLE
Cant Install iOS Plugin

### ISSUE THREAD

**Issue by ikicapitan** [DrMoriarty/godot-applovin-max#13]
Hi.

I was using Firebase and other of your great plugins, and they work on Android and iOS (Godot 3.4).

But when i try to install AppLovin-Max, the process fails. I'm using NativeLib on Windows 8, and works great with other stuff.

The error only happens if i activate "iOS" installation. With Android it works properly.

As i said, its weird because i already installed other of your creations like Firebase plugins, and even the AppTracking Transparency on iOS. 

I also tried deleting iOS, Android & Plugins folders (to do a fresh install) and dont work.

Here's what debugger saids when i press "Install" on NativeLib:

EDIT: I was doing some investigation and maybe it's related to codification UTF8. But if you look at my path, i dont use any special character or anything.

Installing applovinmax@0.1.1
Traceback (most recent call last):
  File "F:\iki\Disenio y Desarrollo de Videojuegos\Colombia\Trivia Penalty Final 2\addons\NativeLib\nativelib", line 1174, in <module>
    install_package(p, v)
  File "F:\iki\Disenio y Desarrollo de Videojuegos\Colombia\Trivia Penalty Final 2\addons\NativeLib\nativelib", line 943, in install_package
    if not install_package(p, v):
  File "F:\iki\Disenio y Desarrollo de Videojuegos\Colombia\Trivia Penalty Final 2\addons\NativeLib\nativelib", line 948, in install_package
    download_package(package_name, version, package_meta)
  File "F:\iki\Disenio y Desarrollo de Videojuegos\Colombia\Trivia Penalty Final 2\addons\NativeLib\nativelib", line 438, in download_package
    path = download(f['url'], fname, home)
  File "F:\iki\Disenio y Desarrollo de Videojuegos\Colombia\Trivia Penalty Final 2\addons\NativeLib\nativelib", line 413, in download
    (filepath, headers) = urlretrieve(url, os.path.join(path, filename), reporthook=_progress)
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\ikicapitan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

**Comment by ikicapitan** [comment]
I move the path of my project to a shorter path and it works. It seems i was right... it's something with UTF8 decoding something that i dont even know.

Thank you.
