### ISSUE TITLE
Pressing install on NativeLib UI gives a 403

### ISSUE THREAD

**Issue by SanderVanhove** [DrMoriarty/godot-applovin-max#4]
I'm trying to install this ad mediator as it seems to be the only one that woks on Android and iOS, but everytime I press `Install` in the NativeLib UI plugin it gives me this error in the console:

```sh
ERROR: call: Command C:/Python39/python.exe, exit code 1
   At: modules/gdscript/gdscript_functions.cpp:803
Checking project dependencies: nativelib-export@0.1.0
Installing nativelib-export@0.1.0
Traceback (most recent call last):
  File "C:\Users\salam\Projects\Godot\just-jump\src\addons\NativeLib\nativelib", line 1172, in <module>
    install_package(p, v)
  File "C:\Users\salam\Projects\Godot\just-jump\src\addons\NativeLib\nativelib", line 941, in install_package
    if not install_package(p, v):
  File "C:\Users\salam\Projects\Godot\just-jump\src\addons\NativeLib\nativelib", line 946, in install_package
    download_package(package_name, version, package_meta)
  File "C:\Users\salam\Projects\Godot\just-jump\src\addons\NativeLib\nativelib", line 436, in download_package
    path = download(f['url'], fname, home)
  File "C:\Users\salam\Projects\Godot\just-jump\src\addons\NativeLib\nativelib", line 411, in download
    (filepath, headers) = urlretrieve(url, os.path.join(path, filename), reporthook=_progress)
  File "C:\Python39\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I'm using Python 3.9.1 and Godot 3.3.2.stable.

**Comment by DrMoriarty** [comment]
I think that it should be already fixed
